edit-water-modal
AnastasiyaNK/water-tracker-frontend pull request #14
Opened 2024-01-28 22:00 UTC by Igor2109

2024-01-29 08:16 UTC, AnastasiyaNK requested changes

2024-01-29 08:16 UTC, AnastasiyaNK commented on src/assets/icons/Group 4.svg
svg називаються з малої букви без пробілів і з  назвою відповідною minus.svg і т.д

2024-01-29 11:29 UTC, Igor2109 commented
Ok
Виправлю)

пн, 29.01.2024 о 09:16 AnastasiyaNK ***@***.***> пише:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> On src/assets/icons/Group 4.svg
> <https://github.com/AnastasiyaNK/water-tracker-frontend/pull/14#discussion_r1469214759>
> :
>
> svg називаються з малої букви без пробілів і з назвою відповідною
> minus.svg і т.д
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/AnastasiyaNK/water-tracker-frontend/pull/14#pullrequestreview-1848053690>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A6JLEFOPJRHS5WM64GRVBVDYQ5LF3AVCNFSM6AAAAABCOPIAC2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQNBYGA2TGNRZGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-01 18:38 UTC, AnastasiyaNK approved these changes

2024-02-01 18:38 UTC, merged